### PR TITLE
feat: overstep limit will error

### PR DESCRIPTION
**Pull request by coolme200**

### CODE REVIEW

**Comment by coolme200** [comment]
Find an array bounds when parsing should give an error message

**Comment by ljharb** [comment]
@coolme200 I'd like to consider this PR - but it needs to be rebased on top of latest master (the code and tests has changed a bit). Would you mind updating it?

**Comment by ljharb** [comment]
@coolme200 any interest in completing this?

**Comment by ljharb** [comment]
@fool2fish @coolme200 happy to reopen this if you're still interested in completing it.

**Pull request closed without merging**
