### PR TITLE
allow arrayFormat to take a function

### PR DESCRIPTION
**Pull request by Primajin**
Allow for passing in a function to arrayFormat to help with #219

### CODE REVIEW

**Comment by Primajin** [comment]
Test is failing only on Node 4... but I don't really get why? Is node 4 not able to do ternary operator in variable declarations?

**Comment by ljharb** [comment]
In addition, we’d need similar support for parse, and documentation.

**Comment by Primajin** [comment]
> It’s not failing on node 4, it’s failing on coverage, because this PR needs tests :-)

Oooooh IC. Was scratching my head for a while "Why does node 4 not understand ternaries" 😅 
Yeah alright will take a look then into the parsing part aswell.

Let's see what the community figures out for using this to solve #219 (because I would also really fancy that comma notation)

**Comment by daggerjames** [comment]
any plan to fix this merge? @Primajin

**Comment by ljharb** [comment]
@daggerjames if you'd like to add tests, and can post a link here to your branch (**not** opening another PR), then i can pull them in.

**Comment by Primajin** [comment]
Sure I can fix that - but I haven't figured out yet how this will help us achieve the `a=b,c,d` notation...

**Comment by Primajin** [comment]
@daggerjames what do you think?

**Comment by daggerjames** [comment]
@Primajin 

I check the code and find that there is no 'simple' function that could solve the problem. `generateArrayPrefix` could only generate the prefix part, while 'comma' need to alter the 'key' part. 

I'll look this issue later today, and let you know if I found something new.

**Comment by daggerjames** [comment]
@Primajin check #276

**Comment by Primajin** [comment]
Closing this in favor of #276

**Pull request closed without merging**
