### PR TITLE
[Docs] Add usage instructions for browsers in the README

### PR DESCRIPTION
**Pull request by kabirbaidhya**
Add usage instructions for browsers as the README only has usage for node environment and it is difficult to figure out how to use it in browsers (without using something like browserify/webpack). 

I myself had to go to https://github.com/ljharb/qs/blob/master/dist/qs.js and figure out myself how to do that.

### CODE REVIEW

**Comment by ljharb** [comment]
It's 2016 - you need to be using something like browserify or webpack for all of your JS dependencies. In the next version, I'll be removing `dist/qs.js` entirely from the repo - so I'd prefer not to document a deprecated practice that will soon be removed.

**Comment by kabirbaidhya** [comment]
I understand your point. I'd also rather prefer using browserify/webpack, and we're doing that for all new projects. But what about some old codebases & legacy applications where it's not possible to migrate the existing code into these and are still relying on `<script>` tags. Don't you want to support them?

**Comment by ljharb** [comment]
I do support them by ensuring that `qs` works in browserify - so those users can run it through `browserify --standalone` and put the output in their legacy `vendor` directory.

That's a process that everyone maintaining legacy apps needs to learn, and I don't think this random project's readme is the right place to educate them about that.

**Comment by kabirbaidhya** [comment]
Okay, I got it :+1:

**Comment by ljharb** [comment]
Thanks for the contribution, though, and I hope you're not discouraged from making future ones! <3

**Pull request closed without merging**
