### PR TITLE
[do not merge] make build fail

### PR DESCRIPTION
**Pull request by a0viedo**
oh boy you really have a **lot** of node versions in your travis conf huh...

### CODE REVIEW

**Comment by ljharb** [comment]
lol if you're trying to say that a failed non-master build will fail the overall build badge, i think an english response would have been sufficient :-p

**Comment by a0viedo** [comment]
@ljharb I thought it was quick to reproduce, but badge still remains ok. I guess they changed the default behavior:


Still better to be explicit?

**Comment by ljharb** [comment]
(#165)

**Pull request closed without merging**
